### ISSUE TITLE
[feature] scrum project management

### ISSUE THREAD

**Issue by ceesco53** [canvasowl/ribbbon#5]
Work on a new branch called 'feature/scrum' which will implement the following from the scrum project management approach:

1. Backlog
2. Issues (tag support for things like ux,design,front,back,etc...)
3. Stories
4. Project Owner
5. Assignments
6. Sprints
7. Timeline on dashboard page
8. Burn down
9. Scrum master

I could see someone working on an existing project clicking something that allows them to create a scrum event or a scrum project from an existing ribbbon project.  Someone could also create a new scrum project, or possibly convert an existing project to scrum (that third option would be outside the scope of this issue).

Scrum is something I've grown to love and would like to add these as Ribbbon features under a feature/scrum branch for now.  I think this would make ribbbon fantastic and something I'd definitely use at work pretty much every day.  Timeline for completion of this issue would be in the next month or two (depending on free time, of course).

I'm open to any feedback.

**Comment by canvasowl** [comment]
@ceesco53 for now I would to hold off on this kind of feature. Not saying this wont be possible in the future, but they're some features that I still have coming down teh pipeline in order to to improve Ribbbon before we think about turning this into another agile system. 

I know the benefits and the pitfalls of agile, I just want to make sure it fits within the overall vision of Ribbbon and or that it's implemented the correct way.

So for now, let's hold off on this but this is not off the table and may very well make it in, in the future. 

With that being said production is now running on 5.1
